steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '$REPO_NAME', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME', '--region', 'europe-west2']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']