version: "3.8"
services:
  app:
    build: .
    command: python app.py
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=client_credentials.json